# Generated by Django 6.0.7 on 2026-07-27 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS core;",
            reverse_sql="DROP SCHEMA IF EXISTS core CASCADE;",
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'core"."tenant',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core"."user',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('job_number', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='active', max_length=40)),
                ('geo', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osp_core.tenant')),
            ],
            options={
                'db_table': 'core"."project',
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('height_ft', models.FloatField(blank=True, null=True)),
                ('pole_class', models.CharField(blank=True, max_length=40)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poles', to='osp_core.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osp_core.tenant')),
            ],
            options={
                'db_table': 'core"."pole',
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('app', models.CharField(choices=[('makeready', 'Make-Ready Workstation'), ('redline', 'REDLINE'), ('bim', 'Light Speed BIM'), ('oden', 'ODEN')], max_length=20)),
                ('tier', models.CharField(default='standard', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('seats', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osp_core.tenant')),
            ],
            options={
                'db_table': 'core"."entitlement',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('actor', models.CharField(max_length=200)),
                ('entity', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=60)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osp_core.tenant')),
            ],
            options={
                'db_table': 'core"."audit',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(max_length=60)),
                ('height_ft', models.FloatField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='osp_core.pole')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osp_core.tenant')),
            ],
            options={
                'db_table': 'core"."attachment',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osp_core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='osp_core.user')),
            ],
            options={
                'db_table': 'core"."membership',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['job_number'], name='core_project_jobnum_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('tenant', 'job_number')},
        ),
        migrations.AddIndex(
            model_name='pole',
            index=models.Index(fields=['tag'], name='core_pole_tag_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pole',
            unique_together={('tenant', 'project', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('tenant', 'app')},
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['entity', 'entity_id'], name='core_audit_entity_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('tenant', 'user')},
        ),
    ]
